#!/bin/sh

DESKTOP_SESSION=Lumina
XDG_CURRENT_DESKTOP="${DESKTOP_SESSION}"
#QT_QPA_PLATFORMTHEME=qt5ct
QT_QPA_PLATFORMTHEME=gnome
QT_NO_GLIB=1

export DESKTOP_SESSION
export XDG_CURRENT_DESKTOP
export QT_QPA_PLATFORMTHEME
export QT_NO_GLIB
unset QT_AUTO_SCREEN_SCALE_FACTOR

#OPENBOX_CONFIG="~/.config/lumina-desktop/openbox-rc.xml"

#if [ ! -s "$OPENBOX_CONFIG" ]; then
# cp /etc/xdg/openbox/rc.xml "${OPENBOX_CONFIG}"
#fi

#openbox --config-file "${OPENBOX_CONFIG}" &
openbox &
lumina-desktop
